# _config.yml

title: Your Site Title
description: A collection of your writings.
theme: jekyll-theme-cayman

plugins:
  - jekyll-optional-front-matter

# This block tells Jekyll to automatically apply the "default" layout
# to all files with a .md extension in your repository.
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# This is the plugin that makes the front matter optional.
# It's an extra layer of protection to ensure all your files are processed.
optional_front_matter:
  extensions:
    - .md
  all:
    enabled: true
