# _config.yml

title: Your Site Title
description: A collection of your writings.
theme: jekyll-theme-cayman # or another theme
plugins:
  - jekyll-optional-front-matter

# This is the key part to make your folders work
optional_front_matter:
  all:
    enabled: true
